CREATE TABLE profiles (
    id UUID PRIMARY KEY,
    user_id UUID,
    type VARCHAR(50) NOT NULL,
    expiry_date DATE NOT NULL,
    identity_number VARCHAR(16) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(100) NOT NULL,
    place_of_birth VARCHAR(200) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(20) NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    nationality VARCHAR(100) NOT NULL,
    marital_status VARCHAR(50),
    religion VARCHAR(100),
    address VARCHAR(1024),
    building VARCHAR(255),
    rt VARCHAR(4),
    rw VARCHAR(4),
    province VARCHAR(100),
    document_photo VARCHAR(100),
    occupation VARCHAR(100),
    office_name VARCHAR(100),
    office_address VARCHAR(1024),
    office_phone VARCHAR(20),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
